### ISSUE TITLE
Change border thickness

### ISSUE THREAD

**Issue by Danvor** [showteeth/ggpie#1]
Hi, 
Great package with very useful settings, I wonder if it was possible to make the borders of the pir chart thicker? Am I missing something, since I could not find that flag/option?

Thanks.
Danvor

**Comment by showteeth** [comment]
Hi,
I have added an option `border_size` to change the thickness of the border, you can have a try!  
Notice that you should install from Github with `remotes::install_github("showteeth/ggpie")`, I will upload the updates to CRAN later!

**Comment by Danvor** [comment]
Works great! Thanks.
