### ISSUE TITLE
label text wrap in ggrosepie

### ISSUE THREAD

**Issue by Joesefman** [showteeth/ggpie#2]
Hello, 

how can I please do label text wrapping in ggrosepie, below the code.

ggrosepie(survey, group_key = "x2_what_size_of_organization_do_you_work_for", count_type = "full", label_info = "all",
             show_tick=F,donut_frac=NULL, label_size = 3) 

also, how I can customize the legend box title "x2_what_size_of_organization_do_you_work_for"

![000054](https://user-images.githubusercontent.com/114017246/196038829-d45ea19b-88e0-47ba-be97-425d5402cf9c.png)

**Comment by showteeth** [comment]
Hi,
To customize the legend title, you can `ggrosepie(...) + guides(fill=guide_legend(title="New Legend Title"))`.  
To do label text wrapping, so far there is no simple parameter to do this, I will provide in the next version. Now, you can obtain the plot data with `ggplot_build` and change the data of the text layer, then create plot with modified data.

**Comment by Joesefman** [comment]
Thank you so much for the quick reply I got the first part done, thank you again, as for the ggplot_build I am not sure how to combine them in the Code although I have been to the documentation, if possible you can provide a little more help in this issue to solve the label problem with ggplot_build, meanwhile I will be happy to wait for the next version.

**Comment by showteeth** [comment]
Below is a simple example:
```R
library(ggplot2)
library(ggpie)
data("diamonds")
p = ggrosepie(diamonds, group_key = "color", count_type = "full", label_info = "all",
              show_tick=F,donut_frac=NULL) + guides(fill=guide_legend(title="New Legend Title"))
p.data= ggplot_build(p)
# modify the data
p.data$data[[2]]$label = gsub(pattern = "\\(", replacement = "\n\\(", x=p.data$data[[2]]$label)
grid::grid.newpage()
grid::grid.draw(ggplot_gtable(p.data))
```

**Comment by Joesefman** [comment]
Thank you so so so much, really I appreciate your efforts, in case I want more than two lines, because it's still long and out of the drawing, I attached it here, 
![Screen Shot 2022-10-16 at 9 43 49 PM](https://user-images.githubusercontent.com/114017246/196054960-be59578c-b791-473a-a1cb-6e280bd8fea0.png)
which part I could change or repeat?

**Comment by showteeth** [comment]
The key part is `p.data$data[[2]]$label = ...`, you can change this to whatever length you want.

**Comment by Joesefman** [comment]
Hello again, I have tried hard along with another friend to wrap for multi-lines, but none of us can find a way, I need to know how I can add a line or two or three using p.data$data[[2]]$label = ..., 

I tried something like this p.data$data[[2]]$label = gsub(pattern = "\\&", replacement = "\n\\&", x=p.data$data[[2]]$label)

it wrapped only one value, what do I have to change to control the number of lines please.

also, is there a way to control the rotation of the pie?

![000100](https://user-images.githubusercontent.com/114017246/196229372-0b3a89f3-b239-4abf-9560-3166469d6d07.png)

**Comment by showteeth** [comment]
What do you mean by "add a line or two or three"? What I understand is that you want to split your text into multi-lines, if so, my suggestion is to manual create text instead of using `gsub`,  `gsub` is suitable when you have some pattern in your text. 

`ggpie` does not support the rotation of the pie.

**Comment by showteeth** [comment]
I have added `label_len` which utilizes `stringr::str_wrap` to wrap the text (take effect when `label_split` is set to NULL), you can have a try!

**Comment by Joesefman** [comment]
Thank you for your reply, I updated the package and here is the code:


y <- "x3_how_would_you_describe_the_relationship_between_your_organization_and_your_key_suppliers"
p = ggrosepie(survey, group_key = y , count_type = "full", label_info = "all",label_size = 3, label_len = 5, show_tick=F,donut_frac=NULL) +
        guides(fill=guide_legend(title="Organization size of the participants")) 
p

I have used the documentation for ggrosepie to find the label_len you have added, I could not find it there, please check if the code above can be revised.

<img width="467" alt="Screen Shot 2022-10-20 at 3 58 43 PM" src="https://user-images.githubusercontent.com/114017246/196969543-43020055-753e-4b37-a7ba-4c20cc613c91.png">
<img width="807" alt="Screen Shot 2022-10-20 at 3 59 06 PM" src="https://user-images.githubusercontent.com/114017246/196969559-2398dde1-0d80-4831-a525-18c3e5788344.png">

**Comment by showteeth** [comment]
How did you update the package? Please use this: `remotes::install_github("showteeth/ggpie")`, CRAN usually has a lag.

The code on [GitHub](https://github.com/showteeth/ggpie/blob/2ec7d3608a55b1380d9ad61425829f805e7d14c8/R/ggrosepie.R#L74).

**Comment by Joesefman** [comment]
I've done the update already as instructed I can see the label_len = 4, thank you, however result remains the same, code is below and the pie graph is attached:
![000012](https://user-images.githubusercontent.com/114017246/196989328-6bad8fa3-93e1-4eb4-bead-8443c173f224.png)



```{r}
x <- "x3_how_would_you_describe_the_relationship_between_your_organization_and_your_key_suppliers"
p = ggrosepie(survey, group_key = x , count_type = "full", label_info = "all",label_size = 4, label_split = NULL, label_len = 4,
              show_tick=F,donut_frac=NULL) + guides(fill=guide_legend(title="Organization size of the participants")) 
        
p.data= ggplot_build(p)
grid::grid.newpage()
grid::grid.draw(ggplot_gtable(p.data))
```

**Comment by showteeth** [comment]
I am sorry, I have updated the package, you can have a try!

P.S. there is no need to use:
```R
p.data= ggplot_build(p)
grid::grid.newpage()
grid::grid.draw(ggplot_gtable(p.data))
```

**Comment by Joesefman** [comment]
Hello,
Thank you very much, it worked much better than before :)  , it would be better in the next version to consider the rotation of the pie, it will give your package an advantage as I did not see other packages can do that.  well done and thank you. 
<img width="892" alt="Screen Shot 2022-10-22 at 5 38 45 PM" src="https://user-images.githubusercontent.com/114017246/197348120-d1a56b72-a039-46b9-a412-fa8c4ae434ae.png">
