### ISSUE TITLE
Fix and request

### ISSUE THREAD

**Issue by schonhose** [showteeth/ggpie#3]
Hi,

Thanks for your package. It seems to have exactly what I need: labels outside the plot when they are below a certain threshold. I do have one fix for the function `ggpie`. Please observe the items from the documentation in bold:

**labal**_threshold **Threashold** of the ratio to determine label position (in/out pie). Default: NULL.

I think it should be `label_threshold`.

One other question, regarding the placement of the label outside the plot. Is it possible to provide the y value (probably > 1.5) ourselves to place the label closer to the plot? I really want to limit the length of the space between the label (and the subsequent line to the segment). Hope I have explained this well enough.

**Comment by schonhose** [comment]
More specifically , the `x_nudge` and `y_nudge` in geom_text_greppel are a bit too large for my taste. Perhaps they can be added as a variable (single or for each label) to enhance the output.

**Comment by showteeth** [comment]
Thanks for your kind suggestions, I have corrected the spelling mistakes.

As for the space between the label and the plot, I will fix this tomorrow!

**Comment by showteeth** [comment]
I have added `nudge_x` and `nudge_y`, you can have a try!

Let me know if you have any problems!
