### ISSUE TITLE
label info to include legend 

### ISSUE THREAD

**Issue by akhst7** [showteeth/ggpie#4]
@showteeth, 

Could you include legend as a label info choice  in addition to count, ratio,  and all ?  Also it will be super if it is possible to pick label info choices, for example legend and ratio, or legend and count, or all.  

Thanks.

**Comment by showteeth** [comment]
@akhst7 
Is this the plot you want?
![image](https://user-images.githubusercontent.com/43517166/219546092-06692bc6-67e7-414f-b952-c54242299705.png)

**Comment by akhst7** [comment]
@showteeth 

This looks good. thanks

**Comment by showteeth** [comment]
@akhst7 
I have updated `ggpie` to support this feature, please re-install:
```R
# update you package
remotes::install_github("showteeth/ggpie")

# generate the above plot
ggpie(
    data = diamonds, group_key = "cut", count_type = "full",
    label_info = c("group", "count", "ratio"), label_split = "\n"
  )
```

Please let me know if you need any help.

YB

**Comment by RinconFer** [comment]
Hi, thank you very much for the great package!
Could it be possible to extend the customization of labels to ggrosepie? I would like to be able to plot **only** the percentage without the group name
For example in the image below, I would like to remove the _"OPC|",_ _"AC|"_, _"MES|"_ and _"NPC|"_ text before the percentage
![image](https://github.com/showteeth/ggpie/assets/62716429/1336dbc3-2bc9-46ed-952c-de699d3495c3)

**Comment by showteeth** [comment]
You can try this:
```R
library(ggpie)
library(ggplot2)
data(diamonds)
p = ggrosepie(diamonds,
          group_key = "color", count_type = "full", label_info = "ratio",
          show_tick = FALSE, donut_frac = 0.3, donut_label_size = 3
)
# obtain the data and modify the elements
p.build = ggplot_build(p)
p.build$data[[3]]$label = gsub(pattern = ".*\\|(.*)", replacement = "\\1", p.build$data[[3]]$label)
final.plot <- ggplot_gtable(p.build)
plot(final.plot)
```
![image](https://github.com/showteeth/ggpie/assets/43517166/c8c36530-4424-46fe-98b5-e7551a8f90df)

**Comment by RinconFer** [comment]
Awesome! I have expended a really long time trying to do exactly that, but I don't have enough knowledge on ggplot objects manipulations. Didn't know the function ggplot_build()
Thanks!
